In [96]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [97]:
# Reading the dataset
df = pd.read_csv('../data/raw/checkin_queue_synthetic_2019_2025v2.csv')

In [98]:
df.head()

,Date,Start_Time,End_time,Sector,Airline,Start_Line,End_line,Pax_In_Line,Service_Start,Service_End,...,Luggage_In,Luggage_Out,Line_Type,Queue_Agent,PAX_Left,Flight_Cancelled,Heavy_Flow,Continuous_Flow,Carousel_Stoped,Year
0,2019-11-01,16:00:00,17:00:00,Domestic,Ariline 2,16:37:39,16:50:30,13.0,16:50:33,16:57:49,...,10,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
1,2019-12-09,16:00:00,17:00:00,Domestic,Ariline 1,16:22:02,16:22:34,1.0,16:22:37,16:28:05,...,4,3.0,CK,NaN,NaN,NaN,NaN,NaN,NaN,2019
2,2019-07-05,22:00:00,23:00:00,International,Ariline 10,22:53:55,23:22:16,9.0,23:22:20,23:30:23,...,3,2.0,CK,NaN,NaN,NaN,NaN,NaN,NaN,2019
3,2019-05-11,11:00:00,12:00:00,Domestic,Ariline 1,11:18:01,11:34:07,10.0,11:34:10,11:37:11,...,4,3.0,BD,X,NaN,NaN,NaN,NaN,NaN,2019
4,2019-11-09,17:00:00,18:00:00,Domestic,Ariline 2,17:05:51,17:14:21,0.0,17:14:23,17:19:43,...,1,1.0,PM,X,NaN,NaN,NaN,NaN,NaN,2019

In [99]:
df.shape

(25168, 22)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25168 entries, 0 to 25167
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              25168 non-null  object
 1   Start_Time        25168 non-null  object
 2   End_time          25168 non-null  object
 3   Sector            25168 non-null  object
 4   Airline           25168 non-null  object
 5   Start_Line        25168 non-null  object
 6   End_line          25168 non-null  object
 7   Pax_In_Line       25168 non-null  float64
 8   Service_Start     25168 non-null  object
 9   Service_End       25168 non-null  object
 10  PAX_Served        25168 non-null  int64
 11  Counters          25168 non-null  int64
 12  Luggage_In        25168 non-null  int64
 13  Luggage_Out       25168 non-null  float64
 14  Line_Type         20870 non-null  object
 15  Queue_Agent       10621 non-null  object
 16  PAX_Left          307 non-null    object
 17  Flight_Cancelled  70 non-null     object
 18  Heavy_Flow        499 non-null    object
 19  Continuous_Flow   2481 non-null   object
 20  Carousel_Stoped   888 non-null    object
 21  Year              25168 non-null  int64
dtypes: float64(2), int64(4), object(16)
memory usage: 4.2+ MB

In [101]:
# Removing Unnecessary Columns
columns_to_drop = ['Date', 'Heavy_Flow', 'End_time', 'Continuous_Flow', 'Line_Type', 'Year']
df.drop(columns=columns_to_drop, inplace=True)
df.head()

,Start_Time,Sector,Airline,Start_Line,End_line,Pax_In_Line,Service_Start,Service_End,PAX_Served,Counters,Luggage_In,Luggage_Out,Queue_Agent,PAX_Left,Flight_Cancelled,Carousel_Stoped
0,16:00:00,Domestic,Ariline 2,16:37:39,16:50:30,13.0,16:50:33,16:57:49,4,3,10,7.0,NaN,NaN,NaN,NaN
1,16:00:00,Domestic,Ariline 1,16:22:02,16:22:34,1.0,16:22:37,16:28:05,3,6,4,3.0,NaN,NaN,NaN,NaN
2,22:00:00,International,Ariline 10,22:53:55,23:22:16,9.0,23:22:20,23:30:23,1,7,3,2.0,NaN,NaN,NaN,NaN
3,11:00:00,Domestic,Ariline 1,11:18:01,11:34:07,10.0,11:34:10,11:37:11,3,9,4,3.0,X,NaN,NaN,NaN
4,17:00:00,Domestic,Ariline 2,17:05:51,17:14:21,0.0,17:14:23,17:19:43,1,10,1,1.0,X,NaN,NaN,NaN

In [102]:
# removing duplicated rows
initial_shape = df.shape
df.drop_duplicates(inplace=True)
final_shape = df.shape
print(f"Initial shape: {initial_shape}, Final shape after removing duplicates: {final_shape}")

Initial shape: (25168, 16), Final shape after removing duplicates: (4141, 16)

In [103]:
# Creating a function to substitute null with 0 and "X" with 1
def clean_column(column):
    column.fillna(0, inplace=True)
    column.replace("X", 1, inplace=True)
    return column

In [104]:
# Applying the cleaning function to relevant columns
relevant_columns = ['Queue_Agent', 'PAX_Left', 'Flight_Cancelled','Carousel_Stoped']
for col in relevant_columns:
    df[col] = clean_column(df[col])

/var/folders/fv/sj80_n_s4xggzhpkj9595smm0000gn/T/ipykernel_2060/2490983523.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  column.replace("X", 1, inplace=True)

In [105]:
df.head()

,Start_Time,Sector,Airline,Start_Line,End_line,Pax_In_Line,Service_Start,Service_End,PAX_Served,Counters,Luggage_In,Luggage_Out,Queue_Agent,PAX_Left,Flight_Cancelled,Carousel_Stoped
0,16:00:00,Domestic,Ariline 2,16:37:39,16:50:30,13.0,16:50:33,16:57:49,4,3,10,7.0,0,0,0,0
1,16:00:00,Domestic,Ariline 1,16:22:02,16:22:34,1.0,16:22:37,16:28:05,3,6,4,3.0,0,0,0,0
2,22:00:00,International,Ariline 10,22:53:55,23:22:16,9.0,23:22:20,23:30:23,1,7,3,2.0,0,0,0,0
3,11:00:00,Domestic,Ariline 1,11:18:01,11:34:07,10.0,11:34:10,11:37:11,3,9,4,3.0,1,0,0,0
4,17:00:00,Domestic,Ariline 2,17:05:51,17:14:21,0.0,17:14:23,17:19:43,1,10,1,1.0,1,0,0,0

In [106]:
# Creating a function to convert object columns to time
def convert_to_time(column):
    return pd.to_datetime(column, format='%H:%M:%S')

In [107]:
# Applying the convertion function to relevant columns
time_columns = ['Start_Time', 'Start_Line', 'End_line', 'Service_Start', 'Service_End']
for col in time_columns:
    df[col] = convert_to_time(df[col])

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4141 entries, 0 to 24914
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Start_Time        4141 non-null   datetime64[ns]
 1   Sector            4141 non-null   object
 2   Airline           4141 non-null   object
 3   Start_Line        4141 non-null   datetime64[ns]
 4   End_line          4141 non-null   datetime64[ns]
 5   Pax_In_Line       4141 non-null   float64
 6   Service_Start     4141 non-null   datetime64[ns]
 7   Service_End       4141 non-null   datetime64[ns]
 8   PAX_Served        4141 non-null   int64
 9   Counters          4141 non-null   int64
 10  Luggage_In        4141 non-null   int64
 11  Luggage_Out       4141 non-null   float64
 12  Queue_Agent       4141 non-null   int64
 13  PAX_Left          4141 non-null   int64
 14  Flight_Cancelled  4141 non-null   int64
 15  Carousel_Stoped   4141 non-null   int64
dtypes: datetime64[ns](5), float64(2), int64(7), object(2)
memory usage: 550.0+ KB

In [109]:
df.head()

,Start_Time,Sector,Airline,Start_Line,End_line,Pax_In_Line,Service_Start,Service_End,PAX_Served,Counters,Luggage_In,Luggage_Out,Queue_Agent,PAX_Left,Flight_Cancelled,Carousel_Stoped
0,1900-01-01 16:00:00,Domestic,Ariline 2,1900-01-01 16:37:39,1900-01-01 16:50:30,13.0,1900-01-01 16:50:33,1900-01-01 16:57:49,4,3,10,7.0,0,0,0,0
1,1900-01-01 16:00:00,Domestic,Ariline 1,1900-01-01 16:22:02,1900-01-01 16:22:34,1.0,1900-01-01 16:22:37,1900-01-01 16:28:05,3,6,4,3.0,0,0,0,0
2,1900-01-01 22:00:00,International,Ariline 10,1900-01-01 22:53:55,1900-01-01 23:22:16,9.0,1900-01-01 23:22:20,1900-01-01 23:30:23,1,7,3,2.0,0,0,0,0
3,1900-01-01 11:00:00,Domestic,Ariline 1,1900-01-01 11:18:01,1900-01-01 11:34:07,10.0,1900-01-01 11:34:10,1900-01-01 11:37:11,3,9,4,3.0,1,0,0,0
4,1900-01-01 17:00:00,Domestic,Ariline 2,1900-01-01 17:05:51,1900-01-01 17:14:21,0.0,1900-01-01 17:14:23,1900-01-01 17:19:43,1,10,1,1.0,1,0,0,0

In [110]:
# Creating a function to apply period_of day based on a column in datetime format
def apply_period_of_day(column):
    periods = []
    for time in column.dt.time:
        if time >= pd.to_datetime('05:00:00').time() and time < pd.to_datetime('12:00:00').time():
            periods.append('Morning')
        elif time >= pd.to_datetime('12:00:00').time() and time < pd.to_datetime('17:00:00').time():
            periods.append('Afternoon')
        elif time >= pd.to_datetime('17:00:00').time() and time < pd.to_datetime('21:00:00').time():
            periods.append('Evening')
        else:
            periods.append('Night')
    return periods

In [111]:
# Applying the time conversion function to Start_Time column
df['Period_of_Day'] = apply_period_of_day(df['Start_Time'])

In [112]:
df.head()

,Start_Time,Sector,Airline,Start_Line,End_line,Pax_In_Line,Service_Start,Service_End,PAX_Served,Counters,Luggage_In,Luggage_Out,Queue_Agent,PAX_Left,Flight_Cancelled,Carousel_Stoped,Period_of_Day
0,1900-01-01 16:00:00,Domestic,Ariline 2,1900-01-01 16:37:39,1900-01-01 16:50:30,13.0,1900-01-01 16:50:33,1900-01-01 16:57:49,4,3,10,7.0,0,0,0,0,Afternoon
1,1900-01-01 16:00:00,Domestic,Ariline 1,1900-01-01 16:22:02,1900-01-01 16:22:34,1.0,1900-01-01 16:22:37,1900-01-01 16:28:05,3,6,4,3.0,0,0,0,0,Afternoon
2,1900-01-01 22:00:00,International,Ariline 10,1900-01-01 22:53:55,1900-01-01 23:22:16,9.0,1900-01-01 23:22:20,1900-01-01 23:30:23,1,7,3,2.0,0,0,0,0,Night
3,1900-01-01 11:00:00,Domestic,Ariline 1,1900-01-01 11:18:01,1900-01-01 11:34:07,10.0,1900-01-01 11:34:10,1900-01-01 11:37:11,3,9,4,3.0,1,0,0,0,Morning
4,1900-01-01 17:00:00,Domestic,Ariline 2,1900-01-01 17:05:51,1900-01-01 17:14:21,0.0,1900-01-01 17:14:23,1900-01-01 17:19:43,1,10,1,1.0,1,0,0,0,Evening

In [113]:
# Dropping Start_time column as it's no longer needed
df.drop(columns=['Start_Time'], inplace=True)

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4141 entries, 0 to 24914
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Sector            4141 non-null   object
 1   Airline           4141 non-null   object
 2   Start_Line        4141 non-null   datetime64[ns]
 3   End_line          4141 non-null   datetime64[ns]
 4   Pax_In_Line       4141 non-null   float64
 5   Service_Start     4141 non-null   datetime64[ns]
 6   Service_End       4141 non-null   datetime64[ns]
 7   PAX_Served        4141 non-null   int64
 8   Counters          4141 non-null   int64
 9   Luggage_In        4141 non-null   int64
 10  Luggage_Out       4141 non-null   float64
 11  Queue_Agent       4141 non-null   int64
 12  PAX_Left          4141 non-null   int64
 13  Flight_Cancelled  4141 non-null   int64
 14  Carousel_Stoped   4141 non-null   int64
 15  Period_of_Day     4141 non-null   object
dtypes: datetime64[ns](4), float64(2), int64(7), object(3)
memory usage: 550.0+ KB

In [115]:
# Creating a function to apply one-hot encoding to a categorical column
#def one_hot_encode(column, df):
    #dummies = pd.get_dummies(column, prefix=column.name, dtype=int, drop_first=True)
    #df = pd.concat([df, dummies], axis=1)
    #df.drop(columns=[column.name], inplace=True)
    #return df

In [116]:
# Applying one hot encoding to categorical columns
#categorical_columns = ['Sector', 'Airline', 'Period_of_Day']
#for col in categorical_columns:
    #df = one_hot_encode(df[col], df)

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4141 entries, 0 to 24914
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Sector            4141 non-null   object
 1   Airline           4141 non-null   object
 2   Start_Line        4141 non-null   datetime64[ns]
 3   End_line          4141 non-null   datetime64[ns]
 4   Pax_In_Line       4141 non-null   float64
 5   Service_Start     4141 non-null   datetime64[ns]
 6   Service_End       4141 non-null   datetime64[ns]
 7   PAX_Served        4141 non-null   int64
 8   Counters          4141 non-null   int64
 9   Luggage_In        4141 non-null   int64
 10  Luggage_Out       4141 non-null   float64
 11  Queue_Agent       4141 non-null   int64
 12  PAX_Left          4141 non-null   int64
 13  Flight_Cancelled  4141 non-null   int64
 14  Carousel_Stoped   4141 non-null   int64
 15  Period_of_Day     4141 non-null   object
dtypes: datetime64[ns](4), float64(2), int64(7), object(3)
memory usage: 550.0+ KB

In [118]:
# Creating a function to calculate the duration of events in minutes
def calculate_duration(start_column, end_column):
    duration = (end_column - start_column).dt.total_seconds() / 60.0
    return duration

In [119]:
# Applying function to calculate durations and creating new columns
df['Line_Time'] = calculate_duration(df['Start_Line'], df['End_line'])
df['Service_Time'] = calculate_duration(df['Service_Start'], df['Service_End'])

In [120]:
df['Total_Time'] = df['Line_Time'] + df['Service_Time']

In [121]:
df.head()

,Sector,Airline,Start_Line,End_line,Pax_In_Line,Service_Start,Service_End,PAX_Served,Counters,Luggage_In,Luggage_Out,Queue_Agent,PAX_Left,Flight_Cancelled,Carousel_Stoped,Period_of_Day,Line_Time,Service_Time,Total_Time
0,Domestic,Ariline 2,1900-01-01 16:37:39,1900-01-01 16:50:30,13.0,1900-01-01 16:50:33,1900-01-01 16:57:49,4,3,10,7.0,0,0,0,0,Afternoon,12.850000,7.266667,20.116667
1,Domestic,Ariline 1,1900-01-01 16:22:02,1900-01-01 16:22:34,1.0,1900-01-01 16:22:37,1900-01-01 16:28:05,3,6,4,3.0,0,0,0,0,Afternoon,0.533333,5.466667,6.000000
2,International,Ariline 10,1900-01-01 22:53:55,1900-01-01 23:22:16,9.0,1900-01-01 23:22:20,1900-01-01 23:30:23,1,7,3,2.0,0,0,0,0,Night,28.350000,8.050000,36.400000
3,Domestic,Ariline 1,1900-01-01 11:18:01,1900-01-01 11:34:07,10.0,1900-01-01 11:34:10,1900-01-01 11:37:11,3,9,4,3.0,1,0,0,0,Morning,16.100000,3.016667,19.116667
4,Domestic,Ariline 2,1900-01-01 17:05:51,1900-01-01 17:14:21,0.0,1900-01-01 17:14:23,1900-01-01 17:19:43,1,10,1,1.0,1,0,0,0,Evening,8.500000,5.333333,13.833333

In [122]:
# Dropping datetime columns as they are no longer needed
datetime_columns = ['Start_Line', 'End_line', 'Service_Start', 'Service_End']
df.drop(columns=datetime_columns, inplace=True)

In [123]:
df['Total_Checked_Bags'] = df['Luggage_In'] - df['Luggage_Out']

In [124]:
# Dropping original time columns if not needed
df.drop(columns=['Luggage_In', 'Luggage_Out', 'Line_Time', 'Service_Time'], inplace=True)

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4141 entries, 0 to 24914
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Sector              4141 non-null   object
 1   Airline             4141 non-null   object
 2   Pax_In_Line         4141 non-null   float64
 3   PAX_Served          4141 non-null   int64
 4   Counters            4141 non-null   int64
 5   Queue_Agent         4141 non-null   int64
 6   PAX_Left            4141 non-null   int64
 7   Flight_Cancelled    4141 non-null   int64
 8   Carousel_Stoped     4141 non-null   int64
 9   Period_of_Day       4141 non-null   object
 10  Total_Time          4141 non-null   float64
 11  Total_Checked_Bags  4141 non-null   float64
dtypes: float64(3), int64(6), object(3)
memory usage: 420.6+ KB

In [126]:
# Detection of outliers using IQR method
def detect_outliers_iqr(column):
    Q1 = column.quantile(0.25)
    Q3 = column.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = column[(column < lower_bound) | (column > upper_bound)]
    return outliers

In [127]:
#Checking for outliers in a list of columns
columns_to_check = ['Total_Time']
for col in columns_to_check:
    outliers = detect_outliers_iqr(df[col])
    print(f"Outliers in {col}:")
    print(outliers)
    print("\n")

Outliers in Total_Time:
2        36.400000
19       38.200000
35       38.116667
48       45.650000
53       33.116667
           ...
14643    32.083333
17431    35.866667
18496    39.933333
18699    31.016667
18923    81.733333
Name: Total_Time, Length: 280, dtype: float64

In [128]:
# Creating a function to remove outliers from the dataframe
def remove_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df_cleaned = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
    return df_cleaned

In [129]:
# Applying the functionto remove outliers from relevant columns
for col in columns_to_check:
    df = remove_outliers_iqr(df, col)

In [130]:
df.shape

(3861, 12)

In [131]:
df.describe()

,Pax_In_Line,PAX_Served,Counters,Queue_Agent,PAX_Left,Flight_Cancelled,Carousel_Stoped,Total_Time,Total_Checked_Bags
count,3861.000000,3861.000000,3861.000000,3861.000000,3861.000000,3861.000000,3861.000000,3861.000000,3861.000000
mean,3.594406,1.747475,5.363377,0.423206,0.011396,0.002590,0.030821,8.908236,1.260036
std,4.973683,0.987065,1.859521,0.494132,0.106156,0.050833,0.172855,6.309578,1.042482
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.616667,0.000000
25%,0.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,4.016667,1.000000
50%,2.000000,1.000000,5.000000,0.000000,0.000000,0.000000,0.000000,7.066667,1.000000
75%,5.000000,2.000000,7.000000,1.000000,0.000000,0.000000,0.000000,12.333333,2.000000
max,55.000000,8.000000,12.000000,1.000000,1.000000,1.000000,1.000000,28.666667,7.000000

# Final Verifications

In [132]:
 # Checking for missing values
df.isnull().sum().sum()

0

In [133]:
# Checking for final data types and info
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3861 entries, 0 to 24914
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Sector              3861 non-null   object
 1   Airline             3861 non-null   object
 2   Pax_In_Line         3861 non-null   float64
 3   PAX_Served          3861 non-null   int64
 4   Counters            3861 non-null   int64
 5   Queue_Agent         3861 non-null   int64
 6   PAX_Left            3861 non-null   int64
 7   Flight_Cancelled    3861 non-null   int64
 8   Carousel_Stoped     3861 non-null   int64
 9   Period_of_Day       3861 non-null   object
 10  Total_Time          3861 non-null   float64
 11  Total_Checked_Bags  3861 non-null   float64
dtypes: float64(3), int64(6), object(3)
memory usage: 392.1+ KB

In [134]:
# Shape validation
df.shape

(3861, 12)

In [135]:
# Checking for duplicated rows
df.duplicated().sum().sum()

5

In [136]:
# Dropping duplicated rows if any
df.drop_duplicates(inplace=True)

In [137]:
df.duplicated().sum().sum()

0

In [138]:
# Value range validation
df.describe()

,Pax_In_Line,PAX_Served,Counters,Queue_Agent,PAX_Left,Flight_Cancelled,Carousel_Stoped,Total_Time,Total_Checked_Bags
count,3856.000000,3856.000000,3856.000000,3856.000000,3856.000000,3856.000000,3856.000000,3856.000000,3856.000000
mean,3.596214,1.748185,5.363330,0.422977,0.011411,0.002593,0.030861,8.913045,1.260892
std,4.976164,0.987403,1.859945,0.494096,0.106224,0.050866,0.172963,6.311406,1.042488
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.616667,0.000000
25%,0.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,4.016667,1.000000
50%,2.000000,1.000000,5.000000,0.000000,0.000000,0.000000,0.000000,7.075000,1.000000
75%,5.000000,2.000000,7.000000,1.000000,0.000000,0.000000,0.000000,12.337500,2.000000
max,55.000000,8.000000,12.000000,1.000000,1.000000,1.000000,1.000000,28.666667,7.000000

In [139]:
# checking for VIF (Variance Inflation Factor)
from statsmodels.stats.outliers_influence import variance_inflation_factor
X = df.select_dtypes(include=[np.number])  # Selecting only numeric columns
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
print(vif_data)

              feature       VIF
0         Pax_In_Line  2.404491
1          PAX_Served  5.013542
2            Counters  4.563012
3         Queue_Agent  1.891957
4            PAX_Left  1.052241
5    Flight_Cancelled  1.027351
6     Carousel_Stoped  1.039452
7          Total_Time  4.758586
8  Total_Checked_Bags  3.570097

In [140]:
# Saving the cleaned dataset
df.to_csv('../data/processed/checkin_queue_cleaned.csv', index=False)